lang: en
check-update: true

check-interval-ticks: 40
slowness-level: 0
slowness-duration-ticks: 80
check-thunder: true
check-snow: false

enabled-worlds:
  - "world"
  - "world_nether"
  - "world_the_end"

ignored-biomes:
  - "minecraft:desert"
  - "minecraft:desert_lakes"
  - "minecraft:savanna"
  - "minecraft:savanna_plateau"
  - "minecraft:windswept_savanna"
  - "minecraft:badlands"
  - "minecraft:wooded_badlands"
  - "minecraft:eroded_badlands"